name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  docker:
    uses: marverix/workflows/.github/workflows/docker-bake.yaml@v1
    with:
      docker-user: ${{ vars.DOCKER_USER }}
    secrets:
      docker-pat: ${{ secrets.DOCKER_PAT }}
